# Generated by Django 5.2.3 on 2025-07-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
