# Generated by Django 5.2.3 on 2025-06-23 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_match_status_match_win_name_match_winner_and_more'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='goals',
        ),
        migrations.AddField(
            model_name='voting',
            name='goal_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voting',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.match'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='who_will_win',
            field=models.CharField(choices=[('team_a', 'Team A'), ('team_b', 'Team B')], max_length=100),
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
