# Generated by Django 5.2.3 on 2025-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_voting_goals_voting_goal_difference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
