# Generated by Django 5.2.3 on 2025-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voting_points_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='who_will_win',
            field=models.CharField(choices=[('team_a', 'Team A'), ('team_b', 'Team B'), ('draw', 'Draw')], max_length=100),
        ),
    ]
