# Generated by Django 5.2.3 on 2025-07-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_who_will_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='who_will_win',
            field=models.CharField(blank=True, choices=[('team_a', 'Team A'), ('team_b', 'Team B'), ('draw', 'Draw')], max_length=100, null=True),
        ),
    ]
