# Generated by Django 5.2.3 on 2025-07-28 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_match_match_timezone'),
        ('voting', '0005_alter_voting_who_will_win'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='goal_difference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together={('user', 'match')},
        ),
    ]
