# Generated by Django 5.2.3 on 2025-06-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=400)),
                ('team_b', models.CharField(max_length=400)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('selected_players', models.ManyToManyField(blank=True, to='player.player')),
            ],
        ),
    ]
