# Generated by Django 5.2.3 on 2025-06-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished')], default='upcoming', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='win_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, choices=[('team_a', 'Team A'), ('team_b', 'Team B'), ('draw', 'Draw')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.CharField(max_length=100),
        ),
    ]
