# Generated by Django 5.2.3 on 2025-07-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_match_status_match_win_name_match_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_a_pics',
            field=models.ImageField(blank=True, null=True, upload_to='matches/'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_pics',
            field=models.ImageField(blank=True, null=True, upload_to='matches/'),
        ),
    ]
