# Generated by Django 5.2.3 on 2025-07-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_team_a_pics_match_team_b_pics'),
        ('player', '0002_player_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['date', 'time'], name='match_match_date_6efe2a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='match_match_status_0fe4ae_idx'),
        ),
    ]
