# Generated by Django 5.2.3 on 2025-07-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goal_difference',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
