# Generated by Django 5.2.3 on 2025-07-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_match_goal_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_timezone',
            field=models.CharField(default='UTC', help_text='Timezone of the match (e.g., Asia/Dhaka, America/New_York)', max_length=50),
        ),
    ]
