# Generated by Django 5.2.3 on 2025-08-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_match_points_calculated'),
        ('player', '0003_alter_player_jersey_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date_time']},
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='match_match_date_6efe2a_idx',
        ),
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.AddField(
            model_name='match',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['date_time'], name='match_match_date_ti_b85fb0_idx'),
        ),
    ]
