# Generated by Django 5.2.3 on 2025-08-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_a_pics',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='matches/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_pics',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='matches/'),
        ),
    ]
