# Generated by Django 5.2.3 on 2025-08-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_alter_match_team_a_pics_alter_match_team_b_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished'), ('inactive', 'Inactive')], default='upcoming', max_length=20, null=True),
        ),
    ]
